### PR TITLE
Add jobManager supported sidecars(#176)

### PR DESCRIPTION
**Pull request by Mrart**
Add jobManager supported sidecars,It can used to collect logs ,like filebeat sidecars

### CODE REVIEW

**Comment by functicons** [comment]
Could you try signing the CLA again?

**Comment by functicons** [comment]
Did you use a different email in the commit other than your GitHub account?

**Comment by Mrart** [comment]
> Could you try signing the CLA again?

OK, I will try It tomorrow.

**Comment by Mrart** [comment]
> Did you use a different email in the commit other than your GitHub email?

Do you mean  this "git config --global user.email "mr.artboy@gmail.com" command email address? I think I have config with the github email address.  Tomorrow I will check again.

**Comment by functicons** [comment]
You can check the commit email with `git show <commit>`, is it the same as your GitHub email? I saw 欧阳武林 as the name, but I don't know the email.

**Comment by Mrart** [comment]
@googlebot I fixed it.

**Comment by Mrart** [comment]
@functicons  I have fixed it.

**Comment by Mrart** [comment]
@googlebot I fixed it.

**Comment by Mrart** [comment]
Could you help me close this pr?  I have another pr ,and fixed the commit author

**Comment by functicons** [comment]
Moved to #186

**Pull request closed without merging**
