### PR TITLE
Added missing installation dependencies

### PR DESCRIPTION
**Pull request by csrene**
I installed this operator in minikube on my local machine, and in the way there I noticed some dependencies were not covered by the user guide

### CODE REVIEW

**Comment by functicons** [comment]
Thanks for the PR! Could you specify the version of dependencies? You copy them from the [developer guide](https://github.com/GoogleCloudPlatform/flink-on-k8s-operator/blob/master/docs/developer_guide.md#dependencies)?

**Comment by csrene** [comment]
There, I added the version of the dependencies. sorry for the delay

**Pull request merged**
