### PR TITLE
feat: image pull secret and node selector for flink operator deployment.

### PR DESCRIPTION
**Pull request by Ayush-Singhal28**
This PR add image pull secret and node selector for flink operator deployment.

### CODE REVIEW

**Comment by functicons** [comment]
@hongyegong could you review this PR?

**Comment by Ayush-Singhal28** [comment]
Yes @hongyegong . In our project I build the latest image using master branch. It is under private repo. As we deploy everything with nodeselector. So that workload assign to right node.

**Comment by Ayush-Singhal28** [comment]
@hongyegong @functicons Could you please re-review the PR

**Pull request merged**
