### PR TITLE
Update go module dependency for k8s v1.18

### PR DESCRIPTION
**Pull request by elanv**
Updated go.mod for k8s version 1.18.
Fixed code for updated API.

### CODE REVIEW

**Comment by functicons** [comment]
The CI failed for

```
/root/go/pkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/errors/errors.go:99:10: undefined: errors.Is
note: module requires Go 1.13
make: *** [controller-gen] Error 2
Makefile:60: recipe for target 'controller-gen' failed
The command '/bin/sh -c make build' returned a non-zero code: 2
```

I think we need to update [Dockerfile.builder](https://github.com/GoogleCloudPlatform/flink-on-k8s-operator/blob/master/Dockerfile.builder#L17) to use Go 1.13.

**Comment by elanv** [comment]
> The CI failed for
> 
> ```
> /root/go/pkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/errors/errors.go:99:10: undefined: errors.Is
> note: module requires Go 1.13
> make: *** [controller-gen] Error 2
> Makefile:60: recipe for target 'controller-gen' failed
> The command '/bin/sh -c make build' returned a non-zero code: 2
> ```
> 
> I think we need to update [Dockerfile.builder](https://github.com/GoogleCloudPlatform/flink-on-k8s-operator/blob/master/Dockerfile.builder#L17) to use Go 1.13.

Updated it to 1.14.

**Comment by elanv** [comment]
> Could you update the developer guide for Go version requirement?

Updated.

**Comment by regardfs** [comment]
> > The CI failed for
> > ```
> > /root/go/pkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/errors/errors.go:99:10: undefined: errors.Is
> > note: module requires Go 1.13
> > make: *** [controller-gen] Error 2
> > Makefile:60: recipe for target 'controller-gen' failed
> > The command '/bin/sh -c make build' returned a non-zero code: 2
> > ```
> > 
> > 
> > I think we need to update [Dockerfile.builder](https://github.com/GoogleCloudPlatform/flink-on-k8s-operator/blob/master/Dockerfile.builder#L17) to use Go 1.13.
> 
> Updated it to 1.14 latest.

Go 1.13 is not ready for this project?

**Comment by functicons** [comment]
@regardfs I believe Go 1.13 works, but we want to use the latest version of Go.

**Pull request merged**
