### PR TITLE
Fix truncate history bug

### PR DESCRIPTION
**Pull request by DeliangFan**

### CODE REVIEW

**Review by functicons — CHANGES_REQUESTED** [review]
Could you add a unit test for this method? You might consider refactoring it to make it easier to test. Thanks!

**Comment by DeliangFan** [comment]
> Could you add a unit test for this method? You might consider refactoring it to make it easier to test. Thanks!

A unit test has been added, please take a review again, thanks!

**Review by functicons — APPROVED** [review]

**Review by bains00 — COMMENTED** [review]
Check please

**Pull request merged**
