### PR TITLE
add imagePullSecrets to helm chart value config

### PR DESCRIPTION
**Pull request by hxfxjun**
add imagePullSecrets to helm chart value config

### CODE REVIEW

**Comment by functicons** [comment]
Thanks for the PR! Could you sign the CLA?

**Comment by hxfxjun** [comment]
> @googlebot I signed it!

**Comment by hxfxjun** [comment]
> We found a Contributor License Agreement for you (the sender of this pull request), but were unable to find agreements for all the commit author(s) or Co-authors. If you authored these, maybe you used a different email address in the git commits than was used to sign the CLA ([login here](https://cla.developers.google.com/) to double check)? If these were authored by someone else, then they will need to sign a CLA as well, and confirm that they're okay with these being contributed to Google.
> In order to pass this check, please resolve this problem and then comment `@googlebot I fixed it.`. If the bot doesn't comment, it means it doesn't think anything has changed.
> 
> ℹ️ **Googlers: [Go here](https://goto.google.com/prinfo/https%3A%2F%2Fgithub.com%2FGoogleCloudPlatform%2Fflink-on-k8s-operator%2Fpull%2F410) for more info**.

@googlebot I fixed it.

**Comment by functicons** [comment]
@hxfxjun are you using a different email for the git commit than the github email? They need to be the same.

**Comment by hxfxjun** [comment]
> @hxfxjun are you using a different email for the git commit than the github email? They need to be the same.

ok,thanks

**Pull request closed without merging**
