### PR TITLE
Fixed link to job cluster Helm Chart guide

### PR DESCRIPTION
**Pull request by marcomicera**
There's a [broken link](https://github.com/marcomicera/flink-on-k8s-operator/blob/master/helm-chart/flink-job-cluster/README.md) to the Flink job cluster Helm Chart guide.

### CODE REVIEW

**Review by william-wang — APPROVED** [review]
/lgtm

**Comment by william-wang** [comment]
@marcomicera please make the ci happy :)

**Comment by marcomicera** [comment]
Maybe I'm missing something...

**Comment by medb** [comment]
Thanks for the fix!

**Pull request merged**
