### PR TITLE
Add podLabels to JM, TM, Job

### LINKED ISSUE #319: Add support for custom labels for pods
Support passing on extra labels for the pods (JMs, TMs, job).  
Like `podAnnotations`
This will allow external k8s solutions to work with this operator (that require a label to exist on pod in order to find it)
Adding a PR for this feature.

### PR DESCRIPTION
**Pull request by shashken**
Closes #319

### CODE REVIEW

**Comment by functicons** [comment]
Could you sign the CLA? Thanks!

**Review by functicons — APPROVED** [review]

**Comment by shashken** [comment]
> Could you sign the CLA? Thanks!

Signed. @functicons  Can you please take a look at an issue I opened: #320   
It seems HA works apart from that bug

**Comment by functicons** [comment]
Seems not signed yet, you need to reply `@googlebot I signed it!` in the comment, thanks!

**Pull request merged**
